### ISSUE TITLE
game crash when used with quiltmc

### ISSUE THREAD

**Issue by kenshin33** [TheWinABagel/Decorative-Blocks#2]
Hi, I know it doesn't say explicitly that it works with quilt, but from what I understood most mod will work with both. Is decorative-blocks one f the few that do not?
would it be an easy fix?  I'd more than happy to give it  a try but I have no clue where to start (any pointer are welcome).

Here's a snippet from the  crash log.
``-- Crash --

org.quiltmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:526)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2358.method_10199(class_2358.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:54)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	... 5 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.quiltmc.qsl.tag.api.QuiltTagKey.type()" because "tag" is null
	at net.minecraft.class_6880$class_6883.handler$ecc000$quilt_tags$onIsInStart(class_6880.java:547)
	at net.minecraft.class_6880$class_6883.method_40220(class_6880.java)
	at net.minecraft.class_4970$class_4971.method_26164(class_4970.java:1182)
	at net.minecraft.class_14.handler$bkk000$decorative_blocks$onCheckBurningBlock(class_14.java:1707)
	at net.minecraft.class_14.method_27138(class_14.java)
	at net.minecraft.class_14.method_59(class_14.java:548)
	at net.minecraft.class_4970$class_4971.handler$bcn002$lithium$init(class_4970.java:2353)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:846)
	at net.minecraft.class_2246.<clinit>(class_2246.java:1185)
	... 13 more

-- Mods --

**Comment by kenshin33** [comment]
4.0.3 seem to have fixed the issue  curious as to how and why though.
